using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class GameOver : MonoBehaviour
{
    public GameObject GameOverUI; // Reference to the game over UI GameObject.

    void Update()
    {
        // This Update method appears to check if the player is dead (commented out).
        // You can uncomment and add code here to handle game over conditions.
        // For now, it's commented out and not active.
    }

    // Method to load the main menu.
    public void LoadMenu()
    {
        Time.timeScale = 1f;               // Resume normal time scale.
        SceneManager.LoadScene("MenuDD"); // Load the "MenuDD" scene.
    }
}
